//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.WMP11Slipstreamer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.WMP11Slipstreamer.Localization.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string dlgAbout_ButtonOK {
            get {
                return ResourceManager.GetString("dlgAbout_ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to go to the website.
        /// </summary>
        internal static string dlgAbout_GotoSite {
            get {
                return ResourceManager.GetString("dlgAbout_GotoSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program will slipstream Windows Media Player 11 into your Windows installation source.
        ///
        ///Next time you install Windows, Windows Media Player 11 will already be installed, waiting for you to experience the best in digital entertainment.
        ///
        ///Note: This program is not developed, maintained, endorsed or supported by Microsoft Corporation in any way. 
        ///
        ///Do not complain to Microsoft about any problems arising from the use of this program. Use at your own risk..
        /// </summary>
        internal static string dlgAbout_InfoText {
            get {
                return ResourceManager.GetString("dlgAbout_InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current translation by:.
        /// </summary>
        internal static string dlgAbout_uxLabelTranslated {
            get {
                return ResourceManager.GetString("dlgAbout_uxLabelTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string dlgError_ButtonClose {
            get {
                return ResourceManager.GetString("dlgError_ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &quot;Close&quot; to return to the application..
        /// </summary>
        internal static string dlgError_Footer {
            get {
                return ResourceManager.GetString("dlgError_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occurred in the worker thread.
        ///Please copy the following diagnostic information and post a bug report..
        /// </summary>
        internal static string dlgError_Header {
            get {
                return ResourceManager.GetString("dlgError_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file does not seem to be a valid icon..
        /// </summary>
        internal static string dlgIconError_Text {
            get {
                return ResourceManager.GetString("dlgIconError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading icon.
        /// </summary>
        internal static string dlgIconError_Title {
            get {
                return ResourceManager.GetString("dlgIconError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate custom icon:.
        /// </summary>
        internal static string dlgIconPicker_Title {
            get {
                return ResourceManager.GetString("dlgIconPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during integration:.
        /// </summary>
        internal static string dlgIntegError_Header {
            get {
                return ResourceManager.GetString("dlgIntegError_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Error.
        /// </summary>
        internal static string dlgIntegError_Title {
            get {
                return ResourceManager.GetString("dlgIntegError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string dlgPicker_AllFiles {
            get {
                return ResourceManager.GetString("dlgPicker_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files.
        /// </summary>
        internal static string dlgPicker_ExeFiles {
            get {
                return ResourceManager.GetString("dlgPicker_ExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon files.
        /// </summary>
        internal static string dlgPicker_IconFiles {
            get {
                return ResourceManager.GetString("dlgPicker_IconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select hotfix(es) to integrate into WMP11:.
        /// </summary>
        internal static string dlgPickHotfixes_Title {
            get {
                return ResourceManager.GetString("dlgPickHotfixes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Microsoft® Windows™ source to modify (must contain an &quot;i386&quot; folder):.
        /// </summary>
        internal static string dlgSrcPicker_Header {
            get {
                return ResourceManager.GetString("dlgSrcPicker_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration cancelled by user. Source remains unchanged..
        /// </summary>
        internal static string dlgText_Cancelled {
            get {
                return ResourceManager.GetString("dlgText_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hotfix line specified or some hotfixes in the list do not exist.
        ///
        ///Please reselect hotfixes to integrate and try again..
        /// </summary>
        internal static string dlgText_InvalidHotfixLine {
            get {
                return ResourceManager.GetString("dlgText_InvalidHotfixLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration completed successfully..
        /// </summary>
        internal static string dlgText_Success {
            get {
                return ResourceManager.GetString("dlgText_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essential WMP9 and WMP6.4 files are missing from the specified source.
        ///
        ///Windows Media Player 11 cannot be integrated into a source from which these two components have been removed with nLite or similar source modification utilities..
        /// </summary>
        internal static string dlgText_Wmp64FilesMissing {
            get {
                return ResourceManager.GetString("dlgText_Wmp64FilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Media Player 11 installer could not be found. Please locate it and try again..
        /// </summary>
        internal static string dlgText_WmpRedistNotFound {
            get {
                return ResourceManager.GetString("dlgText_WmpRedistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string dlgTitle_Cancelled {
            get {
                return ResourceManager.GetString("dlgTitle_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Hotfix Line.
        /// </summary>
        internal static string dlgTitle_InvalidHotfixLine {
            get {
                return ResourceManager.GetString("dlgTitle_InvalidHotfixLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string dlgTitle_Success {
            get {
                return ResourceManager.GetString("dlgTitle_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find old WMP components.
        /// </summary>
        internal static string dlgTitle_Wmp64FilesMissing {
            get {
                return ResourceManager.GetString("dlgTitle_Wmp64FilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find WMP11 installer.
        /// </summary>
        internal static string dlgTitle_WmpRedistNotFound {
            get {
                return ResourceManager.GetString("dlgTitle_WmpRedistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMP11Slipstreamer.exe /installer:&quot;wmp11-windowsxp-x86-enu.exe&quot; /winsource:&quot;D:\MyWindowsSource&quot; /hotfix:&quot;D:\Hotfixes|WMPHotfix1.exe|WMPHotfix2.exe&quot; /customicon:&quot;[Boooggy|Vista|Custom]&quot; [/customiconpath:&quot;pathToIcon&quot;] /output:&quot;[Normal|Tweaked]&quot; [/nocats] [/slipstream] [/closeonsuccess]
        ///
        ////installer - Specifies the full path to the Microsoft WMP11 redistributable installer.
        ////winsource - Specifies the Windows source to integrate WMP11 in.
        ////hotfix - Specifies additional WMP11 hotfixes to integrate.
        ////output -  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dlgUsageInfo_Text {
            get {
                return ResourceManager.GetString("dlgUsageInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage information.
        /// </summary>
        internal static string dlgUsageInfo_Title {
            get {
                return ResourceManager.GetString("dlgUsageInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please integrate KB894871 after this process is finished, otherwise the OOBE (out-of-box-experience) wizard will not launch on first boot after installing Windows from this source..
        /// </summary>
        internal static string dlgWarnOobe_Text {
            get {
                return ResourceManager.GetString("dlgWarnOobe_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Out-of-box experience&quot; warning.
        /// </summary>
        internal static string dlgWarnOobe_Title {
            get {
                return ResourceManager.GetString("dlgWarnOobe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please integrate KB908536 after this process is finished, otherwise the &quot;Themes&quot; service will not start after installing Windows from this source..
        /// </summary>
        internal static string dlgWarnUxtheme_Text {
            get {
                return ResourceManager.GetString("dlgWarnUxtheme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Themes&quot; service warning.
        /// </summary>
        internal static string dlgWarnUxtheme_Title {
            get {
                return ResourceManager.GetString("dlgWarnUxtheme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate WMP11 installer (eg: wmp11-windowsxp-x86-enu.exe):.
        /// </summary>
        internal static string dlgWMPRedistPicker_Header {
            get {
                return ResourceManager.GetString("dlgWMPRedistPicker_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not have the expected elements. Unable to verify compatibility..
        /// </summary>
        internal static string errControlXmlInvalid {
            get {
                return ResourceManager.GetString("errControlXmlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta API failed to apply patch &quot;{0}&quot; to the file &quot;{1}&quot;..
        /// </summary>
        internal static string errDeltaAPIFailed {
            get {
                return ResourceManager.GetString("errDeltaAPIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirId: &quot;{0}&quot; is defined more than once in &quot;{1}&quot;.
        /// </summary>
        internal static string errDirIdDuplicated {
            get {
                return ResourceManager.GetString("errDirIdDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hotfix you are trying to slipstream ({0}) is not designed for your target source&apos;s CPU architecture.
        ///Make sure both are 32-bit or x64 versions..
        /// </summary>
        internal static string errHotfixArchMismatch {
            get {
                return ResourceManager.GetString("errHotfixArchMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key in [WinntDirectories] section in &quot;{0}&quot;: &quot;{1}&quot;.
        /// </summary>
        internal static string errInvalidKeyInWinntDirs {
            get {
                return ResourceManager.GetString("errInvalidKeyInWinntDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not seem to contain a valid Windows™ source..
        /// </summary>
        internal static string errInvalidSource {
            get {
                return ResourceManager.GetString("errInvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not seem to contain a valid 32-bit Windows™ source..
        /// </summary>
        internal static string errInvalidX32Src {
            get {
                return ResourceManager.GetString("errInvalidX32Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not seem to contain a valid x64 Windows™ source..
        /// </summary>
        internal static string errInvalidX64Src {
            get {
                return ResourceManager.GetString("errInvalidX64Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The essential setup file &quot;{0}&quot; is missing from this source. This source is corrupt..
        /// </summary>
        internal static string errMissingSetupFileFromArch {
            get {
                return ResourceManager.GetString("errMissingSetupFileFromArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the index of the 32-bit &quot;i386&quot; folder. This x64 source is corrupt..
        /// </summary>
        internal static string errNoI386RefInX64Src {
            get {
                return ResourceManager.GetString("errNoI386RefInX64Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a suitable information file in &quot;{0}&quot;..
        /// </summary>
        internal static string errNoInfInHotfix {
            get {
                return ResourceManager.GetString("errNoInfInHotfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offending hotfix.
        /// </summary>
        internal static string errOffendingFix {
            get {
                return ResourceManager.GetString("errOffendingFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot integrate WMP11 on a windows source of this type..
        /// </summary>
        internal static string errSourceNotSupported {
            get {
                return ResourceManager.GetString("errSourceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to detect the source info for this installation source. Unable to select correct fileset..
        /// </summary>
        internal static string errSrcTypeDetectFail {
            get {
                return ResourceManager.GetString("errSrcTypeDetectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to integrate a non-WMP11 hotfix. Offending file: &quot;{0}&quot;, belongs to hotfix {1}
        ///
        ///You may need an updated version of this program to properly integrate this hotfix..
        /// </summary>
        internal static string errUnsupportedFixAttempt {
            get {
                return ResourceManager.GetString("errUnsupportedFixAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of the Windows Media Player 11 installer is not compatible with your OS installation source.
        ///Make sure that both are 32-bit or x64 versions..
        /// </summary>
        internal static string errWmpRedistArchMismatch {
            get {
                return ResourceManager.GetString("errWmpRedistArchMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WMP11 installer selected. Unable to locate control.xml to verify destination source type..
        /// </summary>
        internal static string errWmpRedistNoControlXml {
            get {
                return ResourceManager.GetString("errWmpRedistNoControlXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of the WMP11 installer is not designed for this installation source.
        ///
        ///Current WMP11 installer is designed for: Windows v{0} {1}
        ///Current source: Windows v{2} {3}.
        /// </summary>
        internal static string errWmpRedistWrongVer {
            get {
                return ResourceManager.GetString("errWmpRedistWrongVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string LocalizerCulture {
            get {
                return ResourceManager.GetString("LocalizerCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3270d2f650dacfe8c48f2f66ce3179d7.
        /// </summary>
        internal static string LocalizerKey {
            get {
                return ResourceManager.GetString("LocalizerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n7Epsilon.
        /// </summary>
        internal static string LocalizerName {
            get {
                return ResourceManager.GetString("LocalizerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying custom icon....
        /// </summary>
        internal static string statApplyCustIcon {
            get {
                return ResourceManager.GetString("statApplyCustIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up temporary folders....
        /// </summary>
        internal static string statCleanTemp {
            get {
                return ResourceManager.GetString("statCleanTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing added files....
        /// </summary>
        internal static string statCompressAdded {
            get {
                return ResourceManager.GetString("statCompressAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing security catalogs....
        /// </summary>
        internal static string statCompressCats {
            get {
                return ResourceManager.GetString("statCompressCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing edited files....
        /// </summary>
        internal static string statCompressEdited {
            get {
                return ResourceManager.GetString("statCompressEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing &quot;{0}&quot;....
        /// </summary>
        internal static string statCompressFile {
            get {
                return ResourceManager.GetString("statCompressFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing overwriting files....
        /// </summary>
        internal static string statCompressOverwrite {
            get {
                return ResourceManager.GetString("statCompressOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating &quot;{0}&quot;....
        /// </summary>
        internal static string statCreateCab {
            get {
                return ResourceManager.GetString("statCreateCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting source type....
        /// </summary>
        internal static string statDetectingSource {
            get {
                return ResourceManager.GetString("statDetectingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining overwriting files....
        /// </summary>
        internal static string statDetOverwrite {
            get {
                return ResourceManager.GetString("statDetOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing &quot;{0}&quot;....
        /// </summary>
        internal static string statEditFile {
            get {
                return ResourceManager.GetString("statEditFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting and applying hotfixes....
        /// </summary>
        internal static string statExtractApplyHotfix {
            get {
                return ResourceManager.GetString("statExtractApplyHotfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting &quot;{0}&quot;....
        /// </summary>
        internal static string statExtractFile {
            get {
                return ResourceManager.GetString("statExtractFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Windows Media Player 11 installer....
        /// </summary>
        internal static string statExtractWmpRedist {
            get {
                return ResourceManager.GetString("statExtractWmpRedist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing [txtsetup_dirs] section....
        /// </summary>
        internal static string statFixingTxtsetupDirs {
            get {
                return ResourceManager.GetString("statFixingTxtsetupDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating file list....
        /// </summary>
        internal static string statGenFileList {
            get {
                return ResourceManager.GetString("statGenFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging folders....
        /// </summary>
        internal static string statMergeFolders {
            get {
                return ResourceManager.GetString("statMergeFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to edit files....
        /// </summary>
        internal static string statPrepareEdit {
            get {
                return ResourceManager.GetString("statPrepareEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing fixes....
        /// </summary>
        internal static string statPreparingFixes {
            get {
                return ResourceManager.GetString("statPreparingFixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading core information files....
        /// </summary>
        internal static string statReadCoreInfs {
            get {
                return ResourceManager.GetString("statReadCoreInfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading setup files....
        /// </summary>
        internal static string statReadFiles {
            get {
                return ResourceManager.GetString("statReadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing files in driver cabinet....
        /// </summary>
        internal static string statReplaceInDriverCab {
            get {
                return ResourceManager.GetString("statReplaceInDriverCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving edited files....
        /// </summary>
        internal static string statSavingInis {
            get {
                return ResourceManager.GetString("statSavingInis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for current operation to complete....
        /// </summary>
        internal static string statWaitCancel {
            get {
                return ResourceManager.GetString("statWaitCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string uxButtonCancel {
            get {
                return ResourceManager.GetString("uxButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string uxButtonExit {
            get {
                return ResourceManager.GetString("uxButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Integrate.
        /// </summary>
        internal static string uxButtonIntegrate {
            get {
                return ResourceManager.GetString("uxButtonIntegrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a custom icon for wmplayer.exe.
        /// </summary>
        internal static string uxCheckboxCustomIcon {
            get {
                return ResourceManager.GetString("uxCheckboxCustomIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not add security catalogs (for those who disable Windows File Protection).
        /// </summary>
        internal static string uxCheckboxNoCats {
            get {
                return ResourceManager.GetString("uxCheckboxNoCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        internal static string uxGroupBoxAdvOpts {
            get {
                return ResourceManager.GetString("uxGroupBoxAdvOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Options.
        /// </summary>
        internal static string uxGroupBoxBasicOpts {
            get {
                return ResourceManager.GetString("uxGroupBoxBasicOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose WMP11 output type:.
        /// </summary>
        internal static string uxLabelChooseType {
            get {
                return ResourceManager.GetString("uxLabelChooseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Operations.
        /// </summary>
        internal static string uxLabelDefaultOp {
            get {
                return ResourceManager.GetString("uxLabelDefaultOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the &quot;...&quot; button to select WMP11 hotfixes to integrate:.
        /// </summary>
        internal static string uxLabelEnterHotfixLine {
            get {
                return ResourceManager.GetString("uxLabelEnterHotfixLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the path to the Windows source to integrate WMP11 in (must contain a &quot;i386&quot; folder):.
        /// </summary>
        internal static string uxLabelEnterSrcPath {
            get {
                return ResourceManager.GetString("uxLabelEnterSrcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the full path to the Media Player 11 installation file or use the &quot;...&quot; button to locate it:.
        /// </summary>
        internal static string uxLabelEnterWMPRedistPath {
            get {
                return ResourceManager.GetString("uxLabelEnterWMPRedistPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview:.
        /// </summary>
        internal static string uxLabelPreview {
            get {
                return ResourceManager.GetString("uxLabelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string uxLinkAbout {
            get {
                return ResourceManager.GetString("uxLinkAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have the installation file, click here to download it (Genuine Windows required).
        /// </summary>
        internal static string uxLinkWMPRedist {
            get {
                return ResourceManager.GetString("uxLinkWMPRedist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string uxRightToLeft {
            get {
                return ResourceManager.GetString("uxRightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string uxStatusBarDefaultText {
            get {
                return ResourceManager.GetString("uxStatusBarDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweaked (with registry tweaks and no WGA).
        /// </summary>
        internal static string uxTypeTweaked {
            get {
                return ResourceManager.GetString("uxTypeTweaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanilla (same as original installer with WGA).
        /// </summary>
        internal static string uxTypeVanilla {
            get {
                return ResourceManager.GetString("uxTypeVanilla", resourceCulture);
            }
        }
    }
}
