//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.n7Framework.Epsilon.Slipstreamers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SlipstreamersMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SlipstreamersMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.n7Framework.Epsilon.Slipstreamers.SlipstreamersMsg", typeof(SlipstreamersMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required file is missing from this installation source..
        /// </summary>
        public static string errArchFileNotFound {
            get {
                return ResourceManager.GetString("errArchFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical file is missing from this installation source..
        /// </summary>
        public static string errCriticalArchFileNotFound {
            get {
                return ResourceManager.GetString("errCriticalArchFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected path.
        /// </summary>
        public static string errExpectedPath {
            get {
                return ResourceManager.GetString("errExpectedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        public static string errFileName {
            get {
                return ResourceManager.GetString("errFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file was not found at the expected path..
        /// </summary>
        public static string errFileNotFound {
            get {
                return ResourceManager.GetString("errFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installation source is not supported..
        /// </summary>
        public static string errSourceNotSupported {
            get {
                return ResourceManager.GetString("errSourceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up....
        /// </summary>
        public static string statCleaningUp {
            get {
                return ResourceManager.GetString("statCleaningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging folders....
        /// </summary>
        public static string statMergingFolders {
            get {
                return ResourceManager.GetString("statMergingFolders", resourceCulture);
            }
        }
    }
}
